# Module Two Activity

For the module two activity you are required to produce coding samples in accordance with the requirements in the project guidelines and rubric. This Notebook has been pre-created as a shell for your project submission.

Once your code is complete, you will download this notebook as an HTML file by clicking **File**, then **Download As**, then **HTML (.html)** from the Jupyter menu bar. Validate that your code and final table output is rendered in the html file before submission.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Missing Blocks:</i></b> Ensure that you have clicked <b><mark>Run</mark></b> for all blocks before downloading as an HTML file or the block may be missing from your submission.</span>
</div>

### Data Source Information
The sourcing information for the data sets can be found in the `README.md` file within the data folder.

To use this starter code file, replace the `data/sample_use_only/titanic_raw.csv` with the reference to your selected data from the list below:

- `data/dirty_data.csv`
- `data/business_data.csv`

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>To Begin:</i></b> replace the <mark>data/sample_use_only/titanic_raw.csv</mark> sample data path with the path to your selected data set.</span>
</div>

In [1]:
reference_file = "data/dirty_data.csv"

## Installing Required Packages
If you have additional packages that you would like to use or install, add them to the **requirements.txt** file then run the next block.

In [2]:
!pip install --upgrade pip

Requirement already satisfied: pip in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (26.1.2)

In [3]:
!pip install -r requirements.txt

Requirement already satisfied: ydata-profiling==4.16.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.7.1)
Requirement already satisfied: pydantic>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.30.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.69.0)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.14.6)
Requirement already satisfied: typeguard<5,>=3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.5.2)
Requirement already satisfied: imagehash==4.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.6)
Requirement already satisfied: dacite>=1.8 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.61.0)
Requirement already satisfied: PyWavelets in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: pillow in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from phik<0.13,>=0.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.5.7)
Requirement already satisfied: patsy>=0.5.6 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: typing_extensions>=4.14.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from typeguard<5,>=3->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.16.0)
Requirement already satisfied: attrs>=19.3.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.6.1)
Requirement already satisfied: puremagic in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.30)
Requirement already satisfied: annotated-types>=0.6.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: six>=1.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.16.0)

## Import the Required Packages
If you have additional packages that you would like to import, add them here.

In [4]:
# Import packages used for data cleaning
import pandas as pd
import numpy as np

## Loading the Data
After you have selected your data set that wish to wrangle, replace the reference file path in the code block at the top of this Notebook, then run the following block.

In [5]:
raw_data = pd.read_csv(reference_file)
raw_data.head()

,date,station,PRCP,SNOW,SNWD,TMAX,TMIN,TOBS,WESF,inclement_weather
0,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
1,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
2,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
3,2018-01-02T00:00:00,GHCND:USC00280907,0.0,0.0,-inf,-8.3,-16.1,-12.2,NaN,False
4,2018-01-03T00:00:00,GHCND:USC00280907,0.0,0.0,-inf,-4.4,-13.9,-13.3,NaN,False

# Cleaning the Data
The sections that follow have some pre-templated steps to examine and clean data. The columns or specified attributes will need to be replaced for your respective dataset that you are cleaning. You may also need to add different cleaning options from your reading as this provides an example starting point to work with your selected dataset.

***Remember to add comments as you go.***

## Columns

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the column values are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

In [6]:
# Display all column names in the dataset
raw_data.columns

Index(['date', 'station', 'PRCP', 'SNOW', 'SNWD', 'TMAX', 'TMIN', 'TOBS',
       'WESF', 'inclement_weather'],
      dtype='object')

### Renaming Columns
If any of the columns in your dataset need renamed, you can use the following examples to update your column names.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the column values selected below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example below we want to rename the `PassengerId` column `ID` and the `Pclass` column to say `Class` as we are considering merging this data with another dataset later which will use these columns as shared keys. For this task, we use the `rename()` method and pass in a dictionary mapping the column names to their new names. We can pass `inplace=True` to change our original dataframe instead of getting a new one back, or `inplace=False` to create a new dataframe to compare against our original. In the example, we are creating a new dataframe that we will use for all follow-on cleaning actions.

In [7]:
# Rename abbreviated weather columns to make them easier to understand
clean_data = raw_data.rename(
    columns={
        "date": "Date",
        "station": "Station",
        "PRCP": "Precipitation",
        "SNOW": "Snowfall",
        "SNWD": "SnowDepth",
        "TMAX": "MaxTemperature",
        "TMIN": "MinTemperature",
        "TOBS": "ObservedTemperature",
        "WESF": "WaterEquivalentSnowfall",
        "inclement_weather": "InclementWeather"
    },
    inplace=False
)

clean_data.head()

,Date,Station,Precipitation,Snowfall,SnowDepth,MaxTemperature,MinTemperature,ObservedTemperature,WaterEquivalentSnowfall,InclementWeather
0,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
1,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
2,2018-01-01T00:00:00,?,0.0,0.0,-inf,5505.0,-40.0,NaN,NaN,NaN
3,2018-01-02T00:00:00,GHCND:USC00280907,0.0,0.0,-inf,-8.3,-16.1,-12.2,NaN,False
4,2018-01-03T00:00:00,GHCND:USC00280907,0.0,0.0,-inf,-4.4,-13.9,-13.3,NaN,False

## Working with Missing Values
Lets take a look at the output of `info()` method to get a quick view of additional information about the data set which can help pinpoint missing values and wrong data types.


<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example dataset, we have an index range of 891 entries or rows available in the sample dataset. Using that foundational data, we can examine the null counts to identify which columns may have null, missing or NaN values. In the example dataset, the following columns indicate potential issues in the data: Age, Cabin, and Embarked.

In [8]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     765 non-null    object
 1   Station                  765 non-null    object
 2   Precipitation            765 non-null    float64
 3   Snowfall                 577 non-null    float64
 4   SnowDepth                577 non-null    float64
 5   MaxTemperature           765 non-null    float64
 6   MinTemperature           765 non-null    float64
 7   ObservedTemperature      398 non-null    float64
 8   WaterEquivalentSnowfall  11 non-null     float64
 9   InclementWeather         408 non-null    object
dtypes: float64(7), object(3)
memory usage: 59.9+ KB

### isnull()
We can also use the `isnull()` method to return a dataframe of boolean values where **True** represents missing data.

In [18]:
clean_data.isnull()

,Date,Station,Precipitation,Snowfall,SnowDepth,MaxTemperature,MinTemperature,ObservedTemperature,WaterEquivalentSnowfall,InclementWeather
0,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
760,False,False,False,False,False,False,False,False,True,False
761,False,False,False,False,False,False,False,False,True,False
762,False,False,False,False,False,False,False,False,True,False
763,False,False,False,False,False,False,False,False,True,False
764,False,False,False,False,False,False,False,False,True,False

For the example dataset, since we already saw from the `info()` method that only three columns were impacted by data issues, the output of the `isnull()` method may not be as helpful so we can limit the output for a given column to check for nulls or use the output for other cleaning functions as shown in the example below.

For your selected dataset, you can replace the Column name `Age` with your selected column that you would like to assess expanding on the dataset for additional afflicted columns for cleaning.

In [19]:
# Identify rows with missing observed temperature values
bool_series = pd.isnull(clean_data["ObservedTemperature"])

missing_observed_temperature = clean_data[bool_series]

missing_observed_temperature

Empty DataFrame
Columns: [Date, Station, Precipitation, Snowfall, SnowDepth, MaxTemperature, MinTemperature, ObservedTemperature, WaterEquivalentSnowfall, InclementWeather]
Index: []

### Using Numpy to Find Missing Data using a Dictionary Comprehension
Rather than do this for each column, we can write a function that will use a [dictionary comprehension](https://www.python.org/dev/peps/pep-0274/) to check all the columns for us:

In [20]:
def get_nan_count(clean_data):
    return {
        col: clean_data[clean_data[col].isin([np.nan])].shape[0] for col in clean_data.columns
    }

get_nan_count(clean_data)

{'Date': 0,
 'Station': 0,
 'Precipitation': 0,
 'Snowfall': 0,
 'SnowDepth': 0,
 'MaxTemperature': 0,
 'MinTemperature': 0,
 'ObservedTemperature': 0,
 'WaterEquivalentSnowfall': 754,
 'InclementWeather': 0}

###  Filling Missing Values Using fillna(), replace() and interpolate()
From the example output, there were 177 rows of data that were impacted by missing data from the sample dataset. For your selected dataset you should evaluate your columns you identified with missing or null values and expand to the afflicted columns to clean your respective dataset.

#### Filling Missing Values with a Specific Value Using fillna()
Here in the example, we will fill in the missing `Age` values with an age of `0` based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection.

In [21]:
# Fill missing snowfall values with 0 because no recorded snowfall is treated as none
clean_data["Snowfall"].fillna(0, inplace=True)

# Fill missing snow depth values with 0 because no recorded snow depth is treated as none
clean_data["SnowDepth"].fillna(0, inplace=True)

# Fill missing observed temperatures with the median observed temperature
clean_data["ObservedTemperature"].fillna(
    clean_data["ObservedTemperature"].median(),
    inplace=True
)

# Fill missing inclement weather values with "Unknown"
clean_data["InclementWeather"].fillna("Unknown", inplace=True)

# Display updated information
clean_data.info()

# Display the number of missing values remaining in each column
get_nan_count(clean_data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     765 non-null    object
 1   Station                  765 non-null    object
 2   Precipitation            765 non-null    float64
 3   Snowfall                 765 non-null    float64
 4   SnowDepth                765 non-null    float64
 5   MaxTemperature           765 non-null    float64
 6   MinTemperature           765 non-null    float64
 7   ObservedTemperature      765 non-null    float64
 8   WaterEquivalentSnowfall  11 non-null     float64
 9   InclementWeather         765 non-null    object
dtypes: float64(7), object(3)
memory usage: 59.9+ KB

{'Date': 0,
 'Station': 0,
 'Precipitation': 0,
 'Snowfall': 0,
 'SnowDepth': 0,
 'MaxTemperature': 0,
 'MinTemperature': 0,
 'ObservedTemperature': 0,
 'WaterEquivalentSnowfall': 754,
 'InclementWeather': 0}

If you do not find the info() method helpful to find the missing data, you can use the previously created get_nan_count() we created to view the missing data by column. In the sample dataset you will see there are still two columns with null values to be addressed.

In [22]:
get_nan_count(clean_data)

{'Date': 0,
 'Station': 0,
 'Precipitation': 0,
 'Snowfall': 0,
 'SnowDepth': 0,
 'MaxTemperature': 0,
 'MinTemperature': 0,
 'ObservedTemperature': 0,
 'WaterEquivalentSnowfall': 754,
 'InclementWeather': 0}

<div class="alert alert-block alert-warning">
    <span style="color:black"><b><i>Example Data:</i></b> Your selected dataset is likely to have several columns where the data is missing, create additional code blocks as necessary to clean your data according to the assignment requirements. Here we will clean the columns with different methods to show you different use cases, you will modify the code herein to the methods you feel are appropriate for your selected data set.
</div>

#### Replacing Missing Values Using replace()
Here in the example, we will replace the missing `Embarked` values with an age of `U` to represent **Unknown** based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection.

In [24]:
# Replace missing station values with "Unknown"
clean_data["Station"].replace(to_replace=np.nan, value="Unknown", inplace=True)

# Display updated information
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     765 non-null    object
 1   Station                  765 non-null    object
 2   Precipitation            765 non-null    float64
 3   Snowfall                 765 non-null    float64
 4   SnowDepth                765 non-null    float64
 5   MaxTemperature           765 non-null    float64
 6   MinTemperature           765 non-null    float64
 7   ObservedTemperature      765 non-null    float64
 8   WaterEquivalentSnowfall  11 non-null     float64
 9   InclementWeather         765 non-null    object
dtypes: float64(7), object(3)
memory usage: 59.9+ KB

#### Dropping Missing Values in Pandas Using dropna()
Here in the example, we will drop the column `Cabin` based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection. Keep in mind that if you use dropna() with an axis of 1, where there are nulls or missing values in more than one column, it may drop all columns that have null or missing values.

In [25]:
clean_data.dropna(axis=1, inplace = True )
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 765 non-null    object
 1   Station              765 non-null    object
 2   Precipitation        765 non-null    float64
 3   Snowfall             765 non-null    float64
 4   SnowDepth            765 non-null    float64
 5   MaxTemperature       765 non-null    float64
 6   MinTemperature       765 non-null    float64
 7   ObservedTemperature  765 non-null    float64
 8   InclementWeather     765 non-null    object
dtypes: float64(6), object(3)
memory usage: 53.9+ KB

### Duplicated Records
Some datasets may include duplicated records. 

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the data types are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

The sample dataset does not have any duplicated records, though some code examples will be provided here for your use against your selected dataset, update the actions you would like to take against your selected dataset to clean it to your preference.

In [26]:
clean_data.duplicated()

0      False
1       True
2       True
3      False
4      False
       ...
760    False
761     True
762     True
763    False
764     True
Length: 765, dtype: bool

## Data Types
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the data types are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

You can use either the .dtypes property to view the data types for each column in the data frame, or the .info() method which will provide additional insights into the columns.

In [27]:
clean_data.dtypes

Date                    object
Station                 object
Precipitation          float64
Snowfall               float64
SnowDepth              float64
MaxTemperature         float64
MinTemperature         float64
ObservedTemperature    float64
InclementWeather        object
dtype: object

### Data Type Conversion
If any of the data types in your dataset need to be modified or redefined, you can use the following block to update your column data types.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the columns and data types selected below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example below we want to modify the data values and type for the `Survived` column to represent a `bool`.

If you do not have any type conversions required for your data set, feel free to comment out the existing example and add a comment as applicable in the code block below:

In [29]:
# Convert columns to their appropriate data types
clean_data = clean_data.assign(
    Date=lambda x: pd.to_datetime(x.Date),
    Station=lambda x: x.Station.astype("string"),
    Precipitation=lambda x: x.Precipitation.astype("float"),
    Snowfall=lambda x: x.Snowfall.astype("float"),
    SnowDepth=lambda x: x.SnowDepth.astype("float"),
    MaxTemperature=lambda x: x.MaxTemperature.astype("float"),
    MinTemperature=lambda x: x.MinTemperature.astype("float"),
    ObservedTemperature=lambda x: x.ObservedTemperature.astype("float"),
    InclementWeather=lambda x: x.InclementWeather.astype("bool")
)

clean_data.dtypes

Date                   datetime64[ns]
Station                string[python]
Precipitation                 float64
Snowfall                      float64
SnowDepth                     float64
MaxTemperature                float64
MinTemperature                float64
ObservedTemperature           float64
InclementWeather                 bool
dtype: object

We will take a quick look at the output of the describe method.

In [30]:
clean_data.describe()

/home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages/numpy/lib/function_base.py:4655: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,Date,Precipitation,Snowfall,SnowDepth,MaxTemperature,MinTemperature,ObservedTemperature
count,765,765.000000,765.000000,765.0,765.000000,765.000000,765.00000
mean,2018-07-01 17:07:45.882352896,5.360392,3.169935,NaN,2649.175294,-15.914379,8.47281
min,2018-01-01 00:00:00,0.000000,0.000000,-inf,-11.700000,-40.000000,-16.10000
25%,2018-04-04 00:00:00,0.000000,0.000000,NaN,13.300000,-40.000000,7.80000
50%,2018-07-01 00:00:00,0.000000,0.000000,NaN,32.800000,-11.100000,8.30000
75%,2018-09-28 00:00:00,5.800000,0.000000,0.0,5505.000000,6.700000,9.40000
max,2018-12-31 00:00:00,61.700000,229.000000,inf,5505.000000,23.900000,26.10000
std,NaN,10.002138,21.857101,NaN,2744.156281,24.242849,7.07719

We will now take a look at the top five records in our dataframe before continue the cleaning examples.

In [31]:
clean_data.head()

,Date,Station,Precipitation,Snowfall,SnowDepth,MaxTemperature,MinTemperature,ObservedTemperature,InclementWeather
0,2018-01-01,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
1,2018-01-01,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
2,2018-01-01,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
3,2018-01-02,GHCND:USC00280907,0.0,0.0,-inf,-8.3,-16.1,-12.2,False
4,2018-01-03,GHCND:USC00280907,0.0,0.0,-inf,-4.4,-13.9,-13.3,False

### Categoricals
When choosing which columns to set as categories, you will want to evaluate how many different values are available for the column.
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

Here in the example dataset, there are three values for the `Class` column, there are two values for the `Sex` column, and three values for the `Embarked` column, so we will convert those to categories for furture analysis. All other columns aside from `Survived` column that we converted to a bool, have a variety of values which cannot be easily placed into categories without first creating bins to use as categoricals which will we learn more about in the coming modules.

In [33]:
# Convert appropriate columns to categorical data types
clean_data_with_categories = clean_data.assign(
    Station=clean_data["Station"].astype("category"),
    InclementWeather=clean_data["InclementWeather"].astype("category")
)

clean_data_with_categories.dtypes

Date                   datetime64[ns]
Station                      category
Precipitation                 float64
Snowfall                      float64
SnowDepth                     float64
MaxTemperature                float64
MinTemperature                float64
ObservedTemperature           float64
InclementWeather             category
dtype: object

In [34]:
clean_data_with_categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 765 non-null    datetime64[ns]
 1   Station              765 non-null    category
 2   Precipitation        765 non-null    float64
 3   Snowfall             765 non-null    float64
 4   SnowDepth            765 non-null    float64
 5   MaxTemperature       765 non-null    float64
 6   MinTemperature       765 non-null    float64
 7   ObservedTemperature  765 non-null    float64
 8   InclementWeather     765 non-null    category
dtypes: category(2), datetime64[ns](1), float64(6)
memory usage: 43.7 KB

In [35]:
clean_data_with_categories.describe()

/home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages/numpy/lib/function_base.py:4655: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,Date,Precipitation,Snowfall,SnowDepth,MaxTemperature,MinTemperature,ObservedTemperature
count,765,765.000000,765.000000,765.0,765.000000,765.000000,765.00000
mean,2018-07-01 17:07:45.882352896,5.360392,3.169935,NaN,2649.175294,-15.914379,8.47281
min,2018-01-01 00:00:00,0.000000,0.000000,-inf,-11.700000,-40.000000,-16.10000
25%,2018-04-04 00:00:00,0.000000,0.000000,NaN,13.300000,-40.000000,7.80000
50%,2018-07-01 00:00:00,0.000000,0.000000,NaN,32.800000,-11.100000,8.30000
75%,2018-09-28 00:00:00,5.800000,0.000000,0.0,5505.000000,6.700000,9.40000
max,2018-12-31 00:00:00,61.700000,229.000000,inf,5505.000000,23.900000,26.10000
std,NaN,10.002138,21.857101,NaN,2744.156281,24.242849,7.07719

In [36]:
clean_data_with_categories.describe(include='category')

                  Station InclementWeather
count                 765              765
unique                  2                2
top     GHCND:USC00280907            False
freq                  398              384

## Tabular Format
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output are from the sample data and will not represent your dataset until these blocks are run. Validate your table represents your dataset before activity submission.</span>
</div>

In [37]:
len(clean_data_with_categories)

765

In [38]:
pd.set_option('display.max_rows', None)
clean_data_with_categories

,Date,Station,Precipitation,Snowfall,SnowDepth,MaxTemperature,MinTemperature,ObservedTemperature,InclementWeather
0,2018-01-01,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
1,2018-01-01,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
2,2018-01-01,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
3,2018-01-02,GHCND:USC00280907,0.0,0.0,-inf,-8.3,-16.1,-12.2,False
4,2018-01-03,GHCND:USC00280907,0.0,0.0,-inf,-4.4,-13.9,-13.3,False
5,2018-01-03,GHCND:USC00280907,0.0,0.0,-inf,-4.4,-13.9,-13.3,False
6,2018-01-03,GHCND:USC00280907,0.0,0.0,-inf,-4.4,-13.9,-13.3,False
7,2018-01-04,?,20.6,229.0,inf,5505.0,-40.0,8.3,True
8,2018-01-04,?,20.6,229.0,inf,5505.0,-40.0,8.3,True
9,2018-01-05,?,0.3,0.0,0.0,5505.0,-40.0,8.3,True
10,2018-01-05,?,0.3,0.0,0.0,5505.0,-40.0,8.3,True
11,2018-01-05,GHCND:USC00280907,14.2,127.0,inf,-4.4,-13.9,-13.9,True
12,2018-01-06,GHCND:USC00280907,0.0,0.0,-inf,-10.0,-15.6,-15.0,False
13,2018-01-07,GHCND:USC00280907,0.0,0.0,-inf,-11.7,-17.2,-16.1,False
14,2018-01-07,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
15,2018-01-08,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
16,2018-01-08,GHCND:USC00280907,0.0,0.0,-inf,-7.8,-16.7,-8.3,False
17,2018-01-10,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
18,2018-01-10,GHCND:USC00280907,0.0,0.0,-inf,5.0,-7.8,-7.8,False
19,2018-01-11,GHCND:USC00280907,0.0,0.0,-inf,4.4,-7.8,1.1,False
20,2018-01-12,GHCND:USC00280907,1.3,0.0,-inf,9.4,0.6,7.8,False
21,2018-01-12,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
22,2018-01-12,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
23,2018-01-12,GHCND:USC00280907,1.3,0.0,-inf,9.4,0.6,7.8,False
24,2018-01-12,GHCND:USC00280907,1.3,0.0,-inf,9.4,0.6,7.8,False
25,2018-01-13,?,17.5,0.0,0.0,5505.0,-40.0,8.3,True
26,2018-01-14,GHCND:USC00280907,0.0,0.0,-inf,2.2,-11.1,-11.1,False
27,2018-01-14,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
28,2018-01-14,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
29,2018-01-14,GHCND:USC00280907,0.0,0.0,-inf,2.2,-11.1,-11.1,False
30,2018-01-15,GHCND:USC00280907,0.0,0.0,-inf,-5.0,-11.7,-8.9,False
31,2018-01-16,GHCND:USC00280907,0.0,0.0,-inf,-1.1,-9.4,-4.4,False
32,2018-01-16,GHCND:USC00280907,0.0,0.0,-inf,-1.1,-9.4,-4.4,False
33,2018-01-17,?,4.8,0.0,0.0,5505.0,-40.0,8.3,True
34,2018-01-17,GHCND:USC00280907,3.0,25.0,inf,0.6,-5.0,0.0,True
35,2018-01-17,GHCND:USC00280907,3.0,25.0,inf,0.6,-5.0,0.0,True
36,2018-01-18,GHCND:USC00280907,1.3,13.0,inf,0.0,-11.1,-8.9,True
37,2018-01-18,GHCND:USC00280907,1.3,13.0,inf,0.0,-11.1,-8.9,True
38,2018-01-18,GHCND:USC00280907,1.3,13.0,inf,0.0,-11.1,-8.9,True
39,2018-01-19,GHCND:USC00280907,0.0,0.0,-inf,-1.1,-11.7,-10.6,False
40,2018-01-19,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
41,2018-01-19,GHCND:USC00280907,0.0,0.0,-inf,-1.1,-11.7,-10.6,False
42,2018-01-20,GHCND:USC00280907,0.0,0.0,-inf,2.8,-11.7,0.0,False
43,2018-01-21,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
44,2018-01-21,GHCND:USC00280907,0.0,0.0,-inf,8.3,-3.3,-2.2,False
45,2018-01-22,?,0.3,0.0,0.0,5505.0,-40.0,8.3,True
46,2018-01-23,GHCND:USC00280907,18.0,0.0,-inf,8.9,2.2,5.0,False
47,2018-01-23,?,3.3,0.0,0.0,5505.0,-40.0,8.3,True
48,2018-01-24,GHCND:USC00280907,3.3,0.0,-inf,13.3,3.3,4.4,False
49,2018-01-24,?,5.3,0.0,0.0,5505.0,-40.0,8.3,True
50,2018-01-25,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
51,2018-01-25,GHCND:USC00280907,0.0,0.0,-inf,4.4,-6.7,-4.4,False
52,2018-01-26,GHCND:USC00280907,0.0,0.0,-inf,0.0,-7.2,-6.1,False
53,2018-01-26,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
54,2018-01-26,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
55,2018-01-27,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
56,2018-01-28,GHCND:USC00280907,1.5,0.0,-inf,11.1,-5.0,5.0,False
57,2018-01-28,GHCND:USC00280907,1.5,0.0,-inf,11.1,-5.0,5.0,False
58,2018-01-30,?,1.5,13.0,inf,5505.0,-40.0,8.3,True
59,2018-01-30,GHCND:USC00280907,0.0,0.0,-inf,6.7,-1.7,-0.6,False
60,2018-01-31,GHCND:USC00280907,0.0,0.0,-inf,6.7,-10.0,-8.9,False
61,2018-01-31,GHCND:USC00280907,0.0,0.0,-inf,6.7,-10.0,-8.9,False
62,2018-02-01,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
63,2018-02-01,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
64,2018-02-02,?,3.8,0.0,-inf,5505.0,-40.0,8.3,True
65,2018-02-02,?,3.8,0.0,-inf,5505.0,-40.0,8.3,True
66,2018-02-05,?,21.8,0.0,0.0,5505.0,-40.0,8.3,True
67,2018-02-05,?,21.8,0.0,0.0,5505.0,-40.0,8.3,True
68,2018-02-05,GHCND:USC00280907,19.8,0.0,0.0,2.8,-3.9,2.2,False
69,2018-02-05,GHCND:USC00280907,19.8,0.0,0.0,2.8,-3.9,2.2,False
70,2018-02-05,?,21.8,0.0,0.0,5505.0,-40.0,8.3,True
71,2018-02-05,GHCND:USC00280907,19.8,0.0,0.0,2.8,-3.9,2.2,False
72,2018-02-06,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
73,2018-02-08,GHCND:USC00280907,24.4,25.0,inf,3.3,-5.6,-5.6,True
74,2018-02-08,GHCND:USC00280907,24.4,25.0,inf,3.3,-5.6,-5.6,True
75,2018-02-08,?,24.6,0.0,0.0,5505.0,-40.0,8.3,True
76,2018-02-09,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
77,2018-02-09,GHCND:USC00280907,0.0,0.0,-inf,-1.1,-8.3,-8.3,False
78,2018-02-09,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
79,2018-02-09,GHCND:USC00280907,0.0,0.0,-inf,-1.1,-8.3,-8.3,False
80,2018-02-10,GHCND:USC00280907,0.0,0.0,-inf,0.0,-8.3,0.0,False
81,2018-02-10,GHCND:USC00280907,0.0,0.0,-inf,0.0,-8.3,0.0,False
82,2018-02-10,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
83,2018-02-10,GHCND:USC00280907,0.0,0.0,-inf,0.0,-8.3,0.0,False
84,2018-02-11,GHCND:USC00280907,18.0,0.0,-inf,5.0,0.0,3.3,False
85,2018-02-11,?,31.2,0.0,0.0,5505.0,-40.0,8.3,True
86,2018-02-11,GHCND:USC00280907,18.0,0.0,-inf,5.0,0.0,3.3,False
87,2018-02-12,GHCND:USC00280907,9.4,0.0,-inf,13.9,3.3,3.9,False
88,2018-02-13,GHCND:USC00280907,0.0,0.0,-inf,5.6,-5.0,-4.4,False
89,2018-02-13,GHCND:USC00280907,0.0,0.0,-inf,5.6,-5.0,-4.4,False
90,2018-02-14,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
91,2018-02-14,GHCND:USC00280907,0.5,0.0,-inf,2.2,-4.4,0.0,False
92,2018-02-14,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
93,2018-02-15,?,1.8,0.0,0.0,5505.0,-40.0,8.3,True
94,2018-02-15,GHCND:USC00280907,0.5,0.0,-inf,9.4,-0.6,5.0,False
95,2018-02-15,?,1.8,0.0,0.0,5505.0,-40.0,8.3,True
96,2018-02-16,?,3.3,0.0,0.0,5505.0,-40.0,8.3,True
97,2018-02-16,GHCND:USC00280907,3.3,0.0,-inf,13.3,3.3,10.0,False
98,2018-02-16,GHCND:USC00280907,3.3,0.0,-inf,13.3,3.3,10.0,False
99,2018-02-16,?,3.3,0.0,0.0,5505.0,-40.0,8.3,True
100,2018-02-17,?,1.5,0.0,0.0,5505.0,-40.0,8.3,True
101,2018-02-17,GHCND:USC00280907,0.0,0.0,-inf,13.3,-4.4,-3.3,False
102,2018-02-18,GHCND:USC00280907,18.8,178.0,inf,3.9,-3.9,0.6,True
103,2018-02-19,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
104,2018-02-19,GHCND:USC00280907,0.0,0.0,0.0,5.6,-5.0,-3.3,False
105,2018-02-20,GHCND:USC00280907,1.3,0.0,-inf,7.2,-3.3,7.2,False
106,2018-02-21,GHCND:USC00280907,0.0,0.0,-inf,17.8,6.1,12.8,False
107,2018-02-22,GHCND:USC00280907,8.6,0.0,-inf,23.9,5.6,5.6,False
108,2018-02-22,?,6.1,0.0,0.0,5505.0,-40.0,8.3,True
109,2018-02-23,GHCND:USC00280907,7.4,0.0,-inf,7.2,1.1,2.2,False
110,2018-02-23,GHCND:USC00280907,7.4,0.0,-inf,7.2,1.1,2.2,False
111,2018-02-23,?,6.1,0.0,0.0,5505.0,-40.0,8.3,True
112,2018-02-25,?,21.3,0.0,0.0,5505.0,-40.0,8.3,True
113,2018-02-25,GHCND:USC00280907,16.5,0.0,-inf,11.1,3.9,4.4,False
114,2018-02-26,?,3.0,0.0,0.0,5505.0,-40.0,8.3,True
115,2018-02-27,GHCND:USC00280907,0.0,0.0,-inf,10.6,0.0,0.0,False
116,2018-02-27,GHCND:USC00280907,0.0,0.0,-inf,10.6,0.0,0.0,False
117,2018-02-28,GHCND:USC00280907,0.0,0.0,-inf,12.2,0.0,0.0,False
118,2018-02-28,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
119,2018-02-28,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
120,2018-03-01,GHCND:USC00280907,0.0,0.0,-inf,14.4,0.0,3.9,False
121,2018-03-01,GHCND:USC00280907,0.0,0.0,-inf,14.4,0.0,3.9,False
122,2018-03-01,GHCND:USC00280907,0.0,0.0,-inf,14.4,0.0,3.9,False
123,2018-03-01,GHCND:USC00280907,0.0,0.0,-inf,14.4,0.0,3.9,False
124,2018-03-03,GHCND:USC00280907,25.4,0.0,0.0,2.8,0.0,1.1,False
125,2018-03-03,?,18.0,0.0,0.0,5505.0,-40.0,8.3,True
126,2018-03-04,GHCND:USC00280907,0.0,0.0,-inf,6.1,1.1,2.8,False
127,2018-03-04,GHCND:USC00280907,0.0,0.0,-inf,6.1,1.1,2.8,False
128,2018-03-04,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
129,2018-03-05,GHCND:USC00280907,0.0,0.0,-inf,5.6,-1.1,-1.1,False
130,2018-03-05,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
131,2018-03-06,GHCND:USC00280907,0.0,0.0,-inf,6.1,-2.2,-1.7,False
132,2018-03-06,GHCND:USC00280907,0.0,0.0,-inf,6.1,-2.2,-1.7,False
133,2018-03-06,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
134,2018-03-06,GHCND:USC00280907,0.0,0.0,-inf,6.1,-2.2,-1.7,False
135,2018-03-08,GHCND:USC00280907,48.8,0.0,0.0,1.1,-0.6,1.1,False
136,2018-03-08,GHCND:USC00280907,48.8,0.0,0.0,1.1,-0.6,1.1,False
137,2018-03-08,?,28.4,0.0,0.0,5505.0,-40.0,8.3,True
138,2018-03-08,GHCND:USC00280907,48.8,0.0,0.0,1.1,-0.6,1.1,False
139,2018-03-09,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
140,2018-03-09,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
141,2018-03-10,GHCND:USC00280907,0.0,0.0,-inf,4.4,-1.7,0.0,False
142,2018-03-10,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
143,2018-03-12,GHCND:USC00280907,0.0,0.0,-inf,5.6,-3.9,-3.9,False
144,2018-03-12,GHCND:USC00280907,0.0,0.0,-inf,5.6,-3.9,-3.9,False
145,2018-03-13,GHCND:USC00280907,4.1,51.0,inf,5.6,-3.9,0.0,True
146,2018-03-13,?,3.0,13.0,inf,5505.0,-40.0,8.3,True
147,2018-03-14,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
148,2018-03-15,GHCND:USC00280907,0.0,0.0,-inf,3.3,-2.2,-0.6,False
149,2018-03-15,?,0.3,0.0,-inf,5505.0,-40.0,8.3,True
150,2018-03-16,GHCND:USC00280907,0.0,0.0,-inf,6.7,-1.1,-0.6,False
151,2018-03-16,?,1.8,0.0,0.0,5505.0,-40.0,8.3,True
152,2018-03-17,GHCND:USC00280907,0.0,0.0,-inf,3.9,-3.9,-3.3,False
153,2018-03-17,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
154,2018-03-18,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
155,2018-03-19,GHCND:USC00280907,0.0,0.0,-inf,5.0,-4.4,-3.3,False
156,2018-03-19,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
157,2018-03-19,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
158,2018-03-20,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
159,2018-03-21,?,6.6,114.0,inf,5505.0,-40.0,8.3,True
160,2018-03-21,GHCND:USC00280907,0.0,0.0,-inf,2.8,-2.8,0.6,False
161,2018-03-21,GHCND:USC00280907,0.0,0.0,-inf,2.8,-2.8,0.6,False
162,2018-03-21,?,6.6,114.0,inf,5505.0,-40.0,8.3,True
163,2018-03-22,GHCND:USC00280907,17.3,178.0,inf,1.7,-1.7,0.0,True
164,2018-03-22,GHCND:USC00280907,17.3,178.0,inf,1.7,-1.7,0.0,True
165,2018-03-23,GHCND:USC00280907,0.0,0.0,-inf,8.9,0.0,1.1,False
166,2018-03-23,?,1.8,0.0,0.0,5505.0,-40.0,8.3,True
167,2018-03-23,GHCND:USC00280907,0.0,0.0,-inf,8.9,0.0,1.1,False
168,2018-03-25,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
169,2018-03-25,GHCND:USC00280907,0.0,0.0,-inf,8.3,-1.1,-0.6,False
170,2018-03-25,GHCND:USC00280907,0.0,0.0,-inf,8.3,-1.1,-0.6,False
171,2018-03-26,GHCND:USC00280907,0.0,0.0,-inf,6.1,-3.9,-2.2,False
172,2018-03-26,GHCND:USC00280907,0.0,0.0,-inf,6.1,-3.9,-2.2,False
173,2018-03-26,GHCND:USC00280907,0.0,0.0,-inf,6.1,-3.9,-2.2,False
174,2018-03-27,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
175,2018-03-27,GHCND:USC00280907,0.0,0.0,-inf,10.0,-3.3,-3.3,False
176,2018-03-27,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
177,2018-03-29,GHCND:USC00280907,0.0,0.0,-inf,10.6,1.7,7.2,False
178,2018-03-29,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
179,2018-03-30,?,0.8,0.0,0.0,5505.0,-40.0,8.3,True
180,2018-03-30,?,0.8,0.0,0.0,5505.0,-40.0,8.3,True
181,2018-03-31,?,0.3,0.0,0.0,5505.0,-40.0,8.3,True
182,2018-03-31,GHCND:USC00280907,1.0,0.0,-inf,13.3,1.7,2.8,False
183,2018-03-31,GHCND:USC00280907,1.0,0.0,-inf,13.3,1.7,2.8,False
184,2018-03-31,GHCND:USC00280907,1.0,0.0,-inf,13.3,1.7,2.8,False
185,2018-04-02,GHCND:USC00280907,9.1,127.0,inf,12.8,-1.1,-1.1,True
186,2018-04-02,?,14.0,152.0,inf,5505.0,-40.0,8.3,True
187,2018-04-02,GHCND:USC00280907,9.1,127.0,inf,12.8,-1.1,-1.1,True
188,2018-04-03,?,4.8,0.0,0.0,5505.0,-40.0,8.3,True
189,2018-04-03,?,4.8,0.0,0.0,5505.0,-40.0,8.3,True
190,2018-04-03,?,4.8,0.0,0.0,5505.0,-40.0,8.3,True
191,2018-04-04,GHCND:USC00280907,11.4,0.0,-inf,3.9,-0.6,3.9,False
192,2018-04-04,GHCND:USC00280907,11.4,0.0,-inf,3.9,-0.6,3.9,False
193,2018-04-04,GHCND:USC00280907,11.4,0.0,-inf,3.9,-0.6,3.9,False
194,2018-04-04,GHCND:USC00280907,11.4,0.0,-inf,3.9,-0.6,3.9,False
195,2018-04-05,GHCND:USC00280907,0.3,0.0,-inf,11.7,-0.6,-0.6,False
196,2018-04-05,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
197,2018-04-06,?,0.3,0.0,0.0,5505.0,-40.0,8.3,True
198,2018-04-07,GHCND:USC00280907,0.8,0.0,-inf,13.9,-1.7,2.8,False
199,2018-04-07,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
200,2018-04-08,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
201,2018-04-08,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
202,2018-04-09,GHCND:USC00280907,0.0,0.0,-inf,6.1,-2.2,-1.7,False
203,2018-04-10,GHCND:USC00280907,0.5,0.0,-inf,8.9,-1.7,1.7,False
204,2018-04-10,GHCND:USC00280907,0.5,0.0,-inf,8.9,-1.7,1.7,False
205,2018-04-11,GHCND:USC00280907,0.0,0.0,-inf,8.9,-3.3,-3.3,False
206,2018-04-12,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
207,2018-04-12,GHCND:USC00280907,0.0,0.0,-inf,10.0,-3.3,2.2,False
208,2018-04-12,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
209,2018-04-12,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
210,2018-04-13,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
211,2018-04-13,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
212,2018-04-14,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
213,2018-04-14,GHCND:USC00280907,0.0,0.0,-inf,26.7,11.1,12.8,False
214,2018-04-14,GHCND:USC00280907,0.0,0.0,-inf,26.7,11.1,12.8,False
215,2018-04-14,GHCND:USC00280907,0.0,0.0,-inf,26.7,11.1,12.8,False
216,2018-04-14,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
217,2018-04-15,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
218,2018-04-17,?,26.2,0.0,0.0,5505.0,-40.0,8.3,True
219,2018-04-18,GHCND:USC00280907,0.0,0.0,-inf,7.2,2.2,2.8,False
220,2018-04-18,GHCND:USC00280907,0.0,0.0,-inf,7.2,2.2,2.8,False
221,2018-04-19,?,2.5,0.0,0.0,5505.0,-40.0,8.3,True
222,2018-04-19,GHCND:USC00280907,6.9,0.0,-inf,11.1,2.8,3.9,False
223,2018-04-19,?,2.5,0.0,0.0,5505.0,-40.0,8.3,True
224,2018-04-20,GHCND:USC00280907,1.3,0.0,-inf,7.8,1.7,1.7,False
225,2018-04-22,GHCND:USC00280907,0.0,0.0,-inf,15.6,4.4,7.8,False
226,2018-04-22,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
227,2018-04-22,GHCND:USC00280907,0.0,0.0,-inf,15.6,4.4,7.8,False
228,2018-04-22,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
229,2018-04-23,GHCND:USC00280907,0.0,0.0,-inf,18.3,1.1,1.7,False
230,2018-04-24,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
231,2018-04-25,GHCND:USC00280907,10.2,0.0,-inf,18.9,2.2,10.6,False
232,2018-04-25,GHCND:USC00280907,10.2,0.0,-inf,18.9,2.2,10.6,False
233,2018-04-25,GHCND:USC00280907,10.2,0.0,-inf,18.9,2.2,10.6,False
234,2018-04-25,GHCND:USC00280907,10.2,0.0,-inf,18.9,2.2,10.6,False
235,2018-04-26,GHCND:USC00280907,28.4,0.0,-inf,15.0,10.6,12.2,False
236,2018-04-26,?,9.1,0.0,0.0,5505.0,-40.0,8.3,True
237,2018-04-27,?,1.0,0.0,0.0,5505.0,-40.0,8.3,True
238,2018-04-27,GHCND:USC00280907,0.0,0.0,-inf,20.0,8.9,10.6,False
239,2018-04-27,?,1.0,0.0,0.0,5505.0,-40.0,8.3,True
240,2018-04-28,GHCND:USC00280907,2.8,0.0,-inf,12.8,7.8,9.4,False
241,2018-04-28,?,1.0,0.0,0.0,5505.0,-40.0,8.3,True
242,2018-04-28,?,1.0,0.0,0.0,5505.0,-40.0,8.3,True
243,2018-04-29,?,8.9,0.0,0.0,5505.0,-40.0,8.3,True
244,2018-04-29,GHCND:USC00280907,9.4,0.0,-inf,21.1,8.9,8.9,False
245,2018-04-29,GHCND:USC00280907,9.4,0.0,-inf,21.1,8.9,8.9,False
246,2018-04-29,GHCND:USC00280907,9.4,0.0,-inf,21.1,8.9,8.9,False
247,2018-04-30,GHCND:USC00280907,0.0,0.0,-inf,13.3,7.2,7.2,False
248,2018-05-01,?,2.0,0.0,0.0,5505.0,-40.0,8.3,True
249,2018-05-01,GHCND:USC00280907,1.3,0.0,-inf,9.4,3.3,3.9,False
250,2018-05-01,?,2.0,0.0,0.0,5505.0,-40.0,8.3,True
251,2018-05-02,GHCND:USC00280907,0.0,0.0,-inf,26.1,3.9,11.1,False
252,2018-05-02,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
253,2018-05-03,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
254,2018-05-04,?,0.8,0.0,0.0,5505.0,-40.0,8.3,True
255,2018-05-05,GHCND:USC00280907,0.0,0.0,-inf,28.3,15.0,15.0,False
256,2018-05-05,GHCND:USC00280907,0.0,0.0,-inf,28.3,15.0,15.0,False
257,2018-05-06,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
258,2018-05-06,GHCND:USC00280907,0.8,0.0,-inf,23.9,13.9,13.9,False
259,2018-05-06,GHCND:USC00280907,0.8,0.0,-inf,23.9,13.9,13.9,False
260,2018-05-06,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
261,2018-05-07,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
262,2018-05-07,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
263,2018-05-07,GHCND:USC00280907,5.6,0.0,-inf,16.7,9.4,9.4,False
264,2018-05-07,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
265,2018-05-08,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
266,2018-05-09,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
267,2018-05-10,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
268,2018-05-10,GHCND:USC00280907,0.0,0.0,-inf,26.1,8.9,10.0,False
269,2018-05-10,GHCND:USC00280907,0.0,0.0,-inf,26.1,8.9,10.0,False
270,2018-05-11,?,8.9,0.0,0.0,5505.0,-40.0,8.3,True
271,2018-05-11,GHCND:USC00280907,12.2,0.0,-inf,23.3,10.0,13.9,False
272,2018-05-11,GHCND:USC00280907,12.2,0.0,-inf,23.3,10.0,13.9,False
273,2018-05-11,?,8.9,0.0,0.0,5505.0,-40.0,8.3,True
274,2018-05-12,?,4.8,0.0,0.0,5505.0,-40.0,8.3,True
275,2018-05-12,?,4.8,0.0,0.0,5505.0,-40.0,8.3,True
276,2018-05-12,?,4.8,0.0,0.0,5505.0,-40.0,8.3,True
277,2018-05-12,GHCND:USC00280907,3.0,0.0,-inf,22.2,8.9,10.0,False
278,2018-05-13,GHCND:USC00280907,5.1,0.0,-inf,12.8,9.4,10.6,False
279,2018-05-13,?,2.0,0.0,0.0,5505.0,-40.0,8.3,True
280,2018-05-14,GHCND:USC00280907,5.8,0.0,-inf,11.7,10.0,11.1,False
281,2018-05-15,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
282,2018-05-15,GHCND:USC00280907,0.5,0.0,-inf,23.3,10.6,17.8,False
283,2018-05-17,?,13.7,0.0,0.0,5505.0,-40.0,8.3,True
284,2018-05-17,?,13.7,0.0,0.0,5505.0,-40.0,8.3,True
285,2018-05-18,?,0.8,0.0,0.0,5505.0,-40.0,8.3,True
286,2018-05-19,?,9.7,0.0,0.0,5505.0,-40.0,8.3,True
287,2018-05-19,GHCND:USC00280907,3.0,0.0,-inf,18.9,7.8,8.3,False
288,2018-05-20,?,9.7,0.0,0.0,5505.0,-40.0,8.3,True
289,2018-05-20,?,9.7,0.0,0.0,5505.0,-40.0,8.3,True
290,2018-05-20,GHCND:USC00280907,15.2,0.0,-inf,14.4,7.8,13.9,False
291,2018-05-20,?,9.7,0.0,0.0,5505.0,-40.0,8.3,True
292,2018-05-20,?,9.7,0.0,0.0,5505.0,-40.0,8.3,True
293,2018-05-20,?,9.7,0.0,0.0,5505.0,-40.0,8.3,True
294,2018-05-21,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
295,2018-05-21,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
296,2018-05-21,GHCND:USC00280907,0.8,0.0,-inf,27.2,12.8,13.3,False
297,2018-05-22,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
298,2018-05-23,GHCND:USC00280907,16.8,0.0,-inf,19.4,13.3,16.1,False
299,2018-05-23,?,17.0,0.0,0.0,5505.0,-40.0,8.3,True
300,2018-05-24,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
301,2018-05-24,GHCND:USC00280907,0.0,0.0,-inf,26.1,15.0,15.6,False
302,2018-05-25,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
303,2018-05-26,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
304,2018-05-26,GHCND:USC00280907,0.0,0.0,-inf,29.4,13.9,20.0,False
305,2018-05-26,GHCND:USC00280907,0.0,0.0,-inf,29.4,13.9,20.0,False
306,2018-05-27,GHCND:USC00280907,1.3,0.0,-inf,31.7,18.3,18.3,False
307,2018-05-27,?,9.4,0.0,0.0,5505.0,-40.0,8.3,True
308,2018-05-27,?,9.4,0.0,0.0,5505.0,-40.0,8.3,True
309,2018-05-27,?,9.4,0.0,0.0,5505.0,-40.0,8.3,True
310,2018-05-28,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
311,2018-05-28,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
312,2018-05-28,?,0.5,0.0,0.0,5505.0,-40.0,8.3,True
313,2018-05-29,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
314,2018-05-30,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
315,2018-05-30,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
316,2018-05-30,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
317,2018-05-30,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
318,2018-05-31,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
319,2018-05-31,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
320,2018-05-31,GHCND:USC00280907,0.0,0.0,-inf,25.6,15.0,16.7,False
321,2018-06-04,?,10.2,0.0,0.0,5505.0,-40.0,8.3,True
322,2018-06-04,GHCND:USC00280907,16.8,0.0,-inf,18.9,10.6,11.1,False
323,2018-06-04,GHCND:USC00280907,16.8,0.0,-inf,18.9,10.6,11.1,False
324,2018-06-04,?,10.2,0.0,0.0,5505.0,-40.0,8.3,True
325,2018-06-05,GHCND:USC00280907,0.0,0.0,-inf,23.3,11.1,12.2,False
326,2018-06-05,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
327,2018-06-06,GHCND:USC00280907,0.0,0.0,-inf,23.3,11.7,13.3,False
328,2018-06-07,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
329,2018-06-07,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
330,2018-06-08,GHCND:USC00280907,0.0,0.0,-inf,22.2,11.7,13.3,False
331,2018-06-08,GHCND:USC00280907,0.0,0.0,-inf,22.2,11.7,13.3,False
332,2018-06-08,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
333,2018-06-08,GHCND:USC00280907,0.0,0.0,-inf,22.2,11.7,13.3,False
334,2018-06-08,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
335,2018-06-09,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
336,2018-06-09,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
337,2018-06-09,?,0.0,0.0,-inf,5505.0,-40.0,8.3,True
338,2018-06-10,GHCND:USC00280907,0.0,0.0,-inf,26.7,16.7,18.9,False